# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7adb31425b7b8ceb0445ec051134070c"
name = "pos-ui"
application_url = "https://lion-antonio-invitations-proudly.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-devs.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lion-antonio-invitations-proudly.trycloudflare.com/auth/callback",
  "https://lion-antonio-invitations-proudly.trycloudflare.com/auth/shopify/callback",
  "https://lion-antonio-invitations-proudly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
